SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY HH:MI:SS') FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, 5) FROM DUAL;
SELECT LAST_DAY(TO_DATE('05-02-2016','DD-MM-YYYY')) FROM DUAL;
SELECT LAST_DAY(TO_DATE('05-02-2017','DD-MM-YYYY')) FROM DUAL;
SELECT MONTHS_BETWEEN(TO_DATE('05-02-2015','DD-MM-YYYY'),TO_DATE('05-02-2017','DD-MM-YYYY')) FROM DUAL;
SELECT NEXT_DAY(TO_DATE('05-02-2017','DD-MM-YYYY'),1) FROM DUAL;